INSERT INTO T_CP_ALUNO 
(CODIGO, NOME, SOBRENOME, CURSO, INSTITUICAO, ANO_INICIO)
VALUES 
(SEQ_CP_ALUNO.NEXTVAL, 'Ronald', 'O Caminhoneiro', 'Desenvolvimento de Sistemas', 'FIAP', 2023);

INSERT INTO T_CP_ALUNO 
(CODIGO, NOME, SOBRENOME, CURSO, INSTITUICAO, ANO_INICIO)
VALUES 
(SEQ_CP_ALUNO.NEXTVAL, 'Lucas', 'Oliveira', 'Sistema da Informação', 'FIAP', 2019);

INSERT INTO T_CP_ALUNO 
(CODIGO, NOME, SOBRENOME, CURSO, INSTITUICAO, ANO_INICIO)
VALUES 
(SEQ_CP_ALUNO.NEXTVAL, 'Clarice', 'Silva', 'Administração', 'FIAP', 2020);